Add dsn format uri
SAP/go-dblib pull request #27
Opened 2021-04-26 10:13 UTC by fwilhelm92

**Description**

This PR adds the function `FormatURI` and its respective unit-tests.
- `FormatURI` can be used to create a connection-string based on a passed input.

**Tests**

- [x] make lint
- [x] make test

2021-04-26 13:10 UTC, cb80 approved these changes

2021-04-27 13:27 UTC, ntnn requested changes

2021-04-27 13:27 UTC, ntnn commented on dsn/format.go
> +// (For more examples see format_test.go)
Without parenthesis.

2021-04-27 13:27 UTC, ntnn commented on dsn/format.go
> +
The empty line can be removed.

2021-04-27 13:27 UTC, ntnn commented on dsn/format.go
> +			return "", fmt.Errorf("FormatURI: failed to transform the value of <%s=%v> to string", key, field.String())
The prefix should be `dsn` instead of `FormatURI`, as that should designate the package the error stems from.

2021-04-27 14:47 UTC, ntnn approved these changes

2021-04-28 05:14 UTC, cb80 submitted a review, later dismissed

2021-05-06 09:44 UTC, ntnn approved these changes

2021-05-06 09:44 UTC, merged